apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: frontend-permissive
  namespace: microservices-demo
spec:
  selector:
    matchLabels:
      app: frontend
  mtls:
    mode: PERMISSIVE
  portLevelMtls:
    3000:
      mode: PERMISSIVE
