apiVersion: v1
kind: Secret
metadata:
  name: demo-consumer-apikey-secret
  namespace: microservices-demo
  labels:
    konghq.com/credential: key-auth
type: Opaque
stringData:
  kongCredType: key-auth
  key: my-secret-api-key-12345
