apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: demo-consumer
  namespace: microservices-demo
  annotations:
    kubernetes.io/ingress.class: kong
username: demo-consumer
credentials:
- demo-consumer-apikey-secret
